INSERT INTO product (name,calories,category_id) VALUES ('Apple',123,1);
INSERT INTO product (name,calories,category_id) VALUES ('Muhomor',2,1);
INSERT INTO product (name,calories,category_id) VALUES ('Eggplant',7531,1);
INSERT INTO product (name,calories,category_id) VALUES ('juice',65,2);
INSERT INTO product (name,calories,category_id) VALUES ('brokkoli',94326,2);
INSERT INTO product (name,calories,category_id) VALUES ('bread',1478,2);
INSERT INTO product (name,calories,category_id) VALUES ('rice',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('antelope',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('bisque',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('buritto',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('chocolate',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('clams',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('dates',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('falafel',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('granola',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('huenos rancheros',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('lobster',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('Waffles',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('Spinach',6,3);
INSERT INTO product (name,calories,category_id) VALUES ('hamburger (and cheeseburgers and bacon cheeseburgers)',6,3);