INSERT INTO category (name) VALUES ('Meat');
INSERT INTO category (name) VALUES ('Milk');
INSERT INTO category (name) VALUES ('Breakfast');
INSERT INTO category (name) VALUES ('Supper');
INSERT INTO category (name) VALUES ('Fruit');
INSERT INTO category (name) VALUES ('Vegetables');
INSERT INTO category (name) VALUES ('Beverages');
INSERT INTO category (name) VALUES ('Baking Mix/Ingredients');
INSERT INTO category (name) VALUES ('Baked Goods');
INSERT INTO category (name) VALUES ('Baby Food');
INSERT INTO category (name) VALUES ('Condiments');
INSERT INTO category (name) VALUES ('Confectionery');
INSERT INTO category (name) VALUES ('Dairy and Eggs');
INSERT INTO category (name) VALUES ('Food Gifts');
INSERT INTO category (name) VALUES ('Frozen Foods');
INSERT INTO category (name) VALUES ('Grains/Cereal/Pasta');